// PRODUCTS
export const GET_TOOLS_BY_NAME = "GET_TOOLS_BY_NAME";
export const GET_TOOLS = "GET_TOOLS";
export const GET_TOOLS_BY_ID = "GET_TOOLS_BY_ID";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const CHANGE_FILTER_CATEGORY = "CHANGE_FILTER_CATEGORY";
export const CHANGE_FILTER_BRAND = "CHANGE_FILTER_BRAND";
export const GET_CATEGORY = "GET_CATEGORY";

// STOCK
export const UPDATE_TOOL_STOCK = "UPDATE_TOOL_STOCK";
export const REGISTER_STOCK_ENTRY_SUCCESS = "REGISTER_STOCK_ENTRY_SUCCESS";
export const REGISTER_STOCK_ENTRY_FAILURE = "REGISTER_STOCK_ENTRY_FAILURE";
export const REGISTER_STOCK_EXIT_SUCCESS = "REGISTER_STOCK_EXIT_SUCCESS";
export const REGISTER_STOCK_EXIT_FAILURE = "REGISTER_STOCK_EXIT_FAILURE";

// USER
export const CREATE_USER = "CREATE_USER";
export const GET_USER = "GET_USER";
export const GET_USER_ID = "GET_USER_ID";
export const GET_USER_ID_ERROR = "GET_USER_ID_ERROR";
export const LOGIN = "LOGIN";
export const VERIFY_LOGIN_SUCCESS = "VERIFY_LOGIN_SUCCESS";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const CERRAR_SESION = "CERRAR_SESION";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const ACTUAL_USER = "ACTUAL_USER";
export const ISAUTHENTICATED = "ISAUTHENTICATED";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const SET_LAST_VISITED_ROUTE = "SET_LAST_VISITED_ROUTE";

// SHIPPING ADDRESS
export const CREATE_SHIPPING_ADDRESS_SUCCESS = "CREATE_SHIPPING_ADDRESS_SUCCESS";
export const CREATE_SHIPPING_ADDRESS_ERROR = "CREATE_SHIPPING_ADDRESS_ERROR";
export const GET_SHIPPING_ADDRESS_SUCCESS = "GET_SHIPPING_ADDRESS_SUCCESS";
export const GET_SHIPPING_ADDRESS_ERROR = "GET_SHIPPING_ADDRESS_ERROR";
export const DELETE_SHIPPING_ADDRESS_SUCCESS = "DELETE_SHIPPING_ADDRESS_SUCCESS";
export const DELETE_SHIPPING_ADDRESS_ERROR = "DELETE_SHIPPING_ADDRESS_ERROR";
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = "UPDATE_SHIPPING_ADDRESS_SUCCESS";
export const UPDATE_SHIPPING_ADDRESS_ERROR = "UPDATE_SHIPPING_ADDRESS_ERROR";
export const SELECT_ADDRESS = "SELECT_ADDRESS";

// ORDERS
export const ORDERS = "ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";

// REVIEWS
export const ADD_REVIEW = "ADD_REVIEW";
export const UPDATE_REVIEW_COMMENTS = "UPDATE_REVIEW_COMMENTS";
export const DELETE_REVIEW = "DELETE_REVIEW";

// CARRITO
export const CREATE_CART_BDD = "CREATE_CART_BDD";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LESS_FROM_CART = "LESS_FROM_CART";
export const DELETE_TROLLEY = "DELETE_TROLLEY";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_ERROR = "PURCHASE_ORDER_ERROR";
export const INTERSECT = "INTERSECT";

// PAGINADO
export const SET_CURRRENT_PAGE = "SET_CURRENT_PAGE";

// BASE DE DATOS
export const CLEAN_BDD = "CLEAN_BDD";
